# example config, update this for your aws account

default_profile = "syd"

# tags added to ec2 instances during launch
additional_tags = { Owner = "alice@little.co", Project = "example project" }

[syd]
region = "ap-southeast-2"
key_name = "my-key"
iam_instance_profile_arn = "arn:aws:iam::123456789012:instance-profile/ec2_my_default"
vpc = { name = "public A", subnet = "subnet-12345678",  security_group = "sg-12345678901234567" }

# include these accounts when listing AMIs
describe_images_owners = "self"

[us]
region = "us-east-1"
key_name = "my-key-us"
iam_instance_profile_arn = "arn:aws:iam::123456789012:instance-profile/ec2_my_default"
vpc = { name = "private B", subnet = "subnet-87654321",  security_group = ["sg-0123456","sg-7123456789"], associate_public_ip_address = true }

# include these accounts when listing AMIs
describe_images_owners = [ "self", "123456789012"]
